### ISSUE TITLE
Outdated spec directory

### ISSUE THREAD

**Issue by dbdr** [opensmiles/opensmiles.github.io#1]
A google search for opensmiles links to pages such as http://opensmiles.org/spec/open-smiles-2-grammar.html
Navigating from there to the TOC shows "DRAFT: 2007-11-13".
If the spec directory is indeed outdated, it should probably be deleted from this repo and from opensmiles.org.

**Comment by rapodaca** [comment]
Hit the same problem, but this time with the url:

http://opensmiles.org/spec/open-smiles.html

This link was also returned by a Google search.

**Comment by johnmay** [comment]
Please note the primary project is https://github.com/opensmiles/OpenSMILES, I'm not sure where these old spec files are from and so am hesitant to delete them if we can't regenerate.
